version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing CI/CD Dependencies...
      - pip3 install flake8 black pytest pytest-astropy pytest-cov
      - pip3 install pytest pytest-astropy pytest-cov
      - pip3 install -r requirements.txt
      - echo ________________________________

      - echo Linting with Black...
      - black --check --diff lambda_function
      - echo ________________________________
      
      - echo Linting with Flake...
      - flake8 --count --max-line-length 88 lambda_function --exclude lambda_function_test_script.py
      - echo ________________________________
      
      - echo Performing Pytest Unit Testing...
      - pytest --pyargs lambda_function --cov lambda_function
      - echo ________________________________
    
  build:
    commands:
      - echo Login to Private ECR (us-east-1)
      - REGION=us-east-1
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 351967858401.dkr.ecr.$REGION.amazonaws.com
      - echo ________________________________
      
      - echo Create Date Tag
      - export TAG=$(date +%Y-%m-%d-%H-%M-%S)
      - echo ________________________________

      - echo Build Docker Image
      - docker build -t 351967858401.dkr.ecr.$REGION.amazonaws.com/sdc_aws_processing_lambda:$TAG lambda_function/.
      - echo ________________________________
      
      - echo Pushing the Docker image...
      - docker push 351967858401.dkr.ecr.$REGION.amazonaws.com/sdc_aws_processing_lambda:$TAG
      - echo ________________________________

      - echo Creating Zip Name...
      - |
        echo "Git Release Tag Script"
        
        TRIGGER=$CODEBUILD_WEBHOOK_TRIGGER
        
        if [[ $TRIGGER == *"tag/"* ]];then
          GIT_TAG=${TRIGGER:4}
          echo "Production Build, tagging with: $TAG"
          docker tag 351967858401.dkr.ecr.$REGION.amazonaws.com/sdc_aws_processing_lambda:$TAG 351967858401.dkr.ecr.$REGION.amazonaws.com/sdc_aws_processing_lambda:$GIT_TAG
          docker push 351967858401.dkr.ecr.us-east-2.amazonaws.com/sdc_aws_processing_lambda:$TAG
        fi
      - echo ________________________________

  post_build:
    commands:
      - echo Build Successful - Lambda Successfully Built and Pushed to ECR